[workspace]

resolver = "2"

members = [
    "crates/dojo-lang",
    "crates/dojo-cli",
    "crates/dojo-indexer",
    "crates/dojo-language-server",
    "crates/dojo-world",
    "crates/dojo-test-runner",
    "crates/dojo-signers",
    "crates/bevy-dojo",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/dojoengine/dojo/"
license = "Apache-2.0"
license-file = "LICENSE"

[workspace.dependencies]
anyhow = "1.0.66"
cairo-vm = "0.3.0-rc1"
cairo-lang-casm = "1.0.0-rc0"
cairo-lang-compiler = "1.0.0-rc0"
cairo-lang-debug = "1.0.0-rc0"
cairo-lang-defs = "1.0.0-rc0"
cairo-lang-diagnostics = "1.0.0-rc0"
cairo-lang-filesystem = "1.0.0-rc0"
cairo-lang-formatter = "1.0.0-rc0"
cairo-lang-language-server = "1.0.0-rc0"
cairo-lang-lowering = "1.0.0-rc0"
cairo-lang-parser = "1.0.0-rc0"
cairo-lang-plugins = "1.0.0-rc0"
cairo-lang-project = "1.0.0-rc0"
cairo-lang-semantic = { version = "1.0.0-rc0", features = ["testing"] }
cairo-lang-sierra-generator = "1.0.0-rc0"
cairo-lang-sierra = "1.0.0-rc0"
cairo-lang-sierra-to-casm = "1.0.0-rc0"
cairo-lang-starknet = "1.0.0-rc0"
cairo-lang-syntax = "1.0.0-rc0"
cairo-lang-test-utils = "1.0.0-rc0"
cairo-lang-test-runner = "1.0.0-rc0"
cairo-lang-utils = "1.0.0-rc0"
camino = { version = "1.1.2", features = ["serde1"] }
chrono = { version = "0.4.24", features = ["serde"] }
clap = { version = "4.2", features = ["derive"] }
colored = "2"
indoc = "1.0.7"
itertools = "0.10.3"
num-bigint = "0.4"
pretty_assertions = "1.2.1"
rayon = "0.9.0"
salsa = "0.16.1"
scarb = { git = "https://github.com/software-mansion/scarb", version = "0.2.0-alpha.2" }
semver = "1.0.5"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0"
smol_str = { version = "0.2.0", features = ["serde"] }
starknet = { git = "https://github.com/xJonathanLEI/starknet-rs", branch = "dev/jsonrpc_0_3_0" }
test-log = "0.2.11"
thiserror = "1.0.32"
toml = "0.4.2"
tracing = "0.1"
tracing-subscriber = "0.3.16"

[patch."https://github.com/starkware-libs/blockifier"]
blockifier = { git = "https://github.com/dojoengine/blockifier", branch = "dev" }

[patch."https://github.com/starkware-libs/starknet-api"]
starknet_api = { git = "https://github.com/dojoengine/starknet-api", branch = "dev" }

[patch.crates-io]
starknet-crypto = { git = "https://github.com/xJonathanLEI/starknet-rs", branch = "dev/jsonrpc_0_3_0" }
cairo-lang-casm = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-compiler = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-debug = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-defs = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-diagnostics = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-filesystem = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-formatter = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-language-server = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-lowering = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-parser = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-plugins = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-project = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-semantic = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-sierra-generator = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-sierra = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-sierra-to-casm = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-starknet = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-syntax = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-test-utils = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-test-runner = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-utils = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
